version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PORT=${PORT:-8080}
      - AUTH_TOKEN=${AUTH_TOKEN}
      - DB_URL=${DB_URL}
      - BOXOFFICE_URL=${BOXOFFICE_URL}
      - BOXOFFICE_API_KEY=${BOXOFFICE_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 5s
      timeout: 3s
      retries: 20

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    volumes:
      - db-data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -P 3306 -uroot -p'${MYSQL_ROOT_PASSWORD}' >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  db-data: