package com.example.moviesapi.BO;/*
 * Movies API
 * Movie service API with the following constraints: - After successful movie creation, synchronously call upstream box office API `GET /boxoffice?title=...`:   * If upstream returns **200**: merge `{revenue, distributor, releaseDate, budget, mpaRating, currency, source, lastUpdated}` into movie record.   * If upstream fails (e.g., **404**): set `boxOffice = null`, do not block creation process. - Rating submission requires authentication (header `X-Rater-Id`), ratings for same `(movieTitle, raterId)` follow **Upsert** semantics. - Rating aggregation returns `{average, count}`, with average rounded to **1 decimal place**. - List search supports `q | year | distributor | budget | mpaRating | genre | limit | cursor`, pagination response is fixed as `items[] + nextCursor`.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



import java.util.List;
import java.util.Map;

/**
 * API response returned by API call.
 */
public record ApiResponse<T>(int statusCode, Map<String, List<String>> headers, T data) {
    /**
     * <p>Constructor for ApiResponse.</p>
     *
     * @param statusCode The status code of HTTP response
     * @param headers    The headers of HTTP response
     */
    public ApiResponse(int statusCode, Map<String, List<String>> headers) {
        this(statusCode, headers, null);
    }

    /**
     * <p>Constructor for ApiResponse.</p>
     *
     * @param statusCode The status code of HTTP response
     * @param headers    The headers of HTTP response
     * @param data       The object deserialized from response bod
     */
    public ApiResponse {
    }

}
